---

- name: Install requirements - pt. 1
  apt: name={{item}} update_cache=yes
  with_items:
    - cron
    - libffi-dev
    - lzop
    - pv
    - python3-dev
    - python3-lxml
    - python3-pip
    - python3-boto
    - python3-boto3
    - python3-botocore
    - python3-dateutil

- name: Install requirements - pt. 2 (legacy)
  pip: executable=pip3 name={{item}}
  with_items: [six, wal-e]
  when: not wale_latest

- name: Install requirements - pt. 2 (latest)
  pip: executable=pip3 name={{item}} state=latest
  with_items: [six, wal-e]
  when: wale_latest
