---

- name: Install requirements - pt. 1
  apt: pkg={{item}}
  with_items:
    - cron
    - lzop
    - pv
    - python-pip
    - python-dev
    - python-lxml

- name: Install requirements - pt. 2
  pip: name={{item}} state=latest
  with_items:
    - six
    - wal-e
