---

- name: Install requirements - pt. 1
  apt: name={{item}} update_cache=yes
  with_items:
    - cron
    - libffi-dev
    - lzop
    - pv
    - python-dev
    - python-lxml
    - python-pip

- name: Install requirements - pt. 2
  pip: name={{item}}
  with_items: [six, wal-e]
  when: not wale_latest

- name: Install requirements - pt. 2
  pip: name={{item}} state=latest
  with_items: [six, wal-e]
  when: wale_latest
