---

- name: Install requirements - pt. 1
  apt: pkg={{item}}
  with_items:
    - cron
    - lzop
    - pv
    - python-pip
    - python-dev
    - python-lxml
    - libffi-dev

- name: Install requirements - pt. 2
  pip: name={{item}}
  with_items: [six, wal-e]
  when: not wale_latest

- name: Install requirements - pt. 2
  pip: name={{item}} state=latest
  with_items: [six, wal-e]
  when: wale_latest
